version: '3.0'
services:
  client:
    tty: true
    build: client
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/src
  api:
    tty: true
    build: api
    ports:
      - 8000:8000
    volumes:
      - ./api/src:/app/src
      - ./api/codes:/app/codes
  mongo-state:
    tty: true
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - 27018:27017
volumes:
  mongo-data: