version: '3.0'
services:
  client:
    tty: true
    build: 
      context: client
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    depends_on:
      - api
    volumes:
      - ./client:/app
      - /app/.next
      - /app/node_modules

  api:
    tty: true
    build: 
      context: api
      dockerfile: Dockerfile.dev
    ports:
      - 8000:8000
    depends_on:
      - mongo-state
    volumes:
      - ./api/src:/app/src
      - ./api/codes:/app/codes
  mongo-state:
    tty: true
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017
volumes:
  mongo-data: