apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: code-challenge-web
build:
  artifacts:
  - image: razmjo/test-api
    context: api
    docker:
      dockerfile: Dockerfile
  - image: razmjo/test-client
    context: client
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/api.deployment.yaml
    - k8s/client.deployment.yaml
    - k8s/ingress-service.yaml
