apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: code-challenge-web
build:
  local:
    push: false
  artifacts:
  - image: us.gcr.io/hiremotely-338114/judge0
    context: judge0
    docker:
      dockerfile: Dockerfile
  - image: us.gcr.io/hiremotely-338114/test-api
    context: api
    docker:
      dockerfile: Dockerfile
  - image: us.gcr.io/hiremotely-338114/test-client
    context: client
    docker:
      dockerfile: Dockerfile
profiles:
  - name: gcb
    build:
      googleCloudBuild:
        projectId: hiremotely-338114
deploy:
  kubectl:
    manifests:
    - k8s/judge0/*
    - k8s/src/**/*
    - k8s/ingress-service.yaml
