apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: code-challenge-web
build:
  local:
    push: false
  artifacts:
  - image: us.gcr.io/hireremotely/test-api
    context: api
    docker:
      dockerfile: Dockerfile
  - image: us.gcr.io/hireremotely/test-client
    context: client
    docker:
      dockerfile: Dockerfile
profiles:
  - name: gcb
    build:
      googleCloudBuild:
        projectId: hireremotely
deploy:
  kubectl:
    manifests:
    - k8s/api.deployment.yaml
    - k8s/client.deployment.yaml
    - k8s/ingress-service.yaml
