apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: code-challenge-web
build:
  local:
    push: false
  artifacts:
  # - image: us.gcr.io/hiremotely-338114/test-api
  - image: razmjo/api
    context: api
    docker:
      dockerfile: Dockerfile
  # - image: us.gcr.io/hiremotely-338114/test-client
  - image: razmjo/client
    context: client
    docker:
      dockerfile: Dockerfile
# s
deploy:
  kubectl:
    manifests:
    - k8s/**/*
