kind: PersistentVolume
apiVersion: v1
metadata:
 name: mongo-pv
 labels:
  type: local
spec:
 storageClassName: manual
 capacity:
  storage: 10Gi
 accessModes:
  - ReadWriteOnce
 hostPath:
  path: /var/lib/data
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
 name: mongo-pv-claim
spec:
 storageClassName: manual
 accessModes:
  - ReadWriteOnce
 resources:
  requests:
   storage: 10Gi
---


apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-state
  namespace: default
spec:
  selector:
    matchLabels:
      app: mongo-state # has to match .spec.template.metadata.labels
  serviceName: "mongo-state"
  replicas: 1 # by default is 1
  template:
    metadata:
      labels:
        app: mongo-state # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      volumes:
        - name: mongo-pv-storage
          persistentVolumeClaim:
            claimName: mongo-pv-claim
      containers:
      - name: mongo-state
        image: mongo:latest
        ports:
        - containerPort: 27017
          name: mongo-container
        volumeMounts:
        - name: mongo-pv-storage
          mountPath: /data/db
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-state
  namespace: default
spec:
  selector:
    app: mongo-state
  type: ClusterIP
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: mongo-state
    protocol: TCP
    port: 27017
    targetPort: 27017