apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          # image: razmjo/api
          image: us.gcr.io/hiremotely-338114/test-api
          env:
            - name: JUDGE0_HOST
              value: https://judge0-ce.p.rapidapi.com
            - name: JUDGE0_KEY
              value: 7afdf2c5eamshf417da207f1ebb4p18e859jsne31b15c5c7ab
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  selector:
    app: api
  type: ClusterIP
  ports:
  - name: api
    protocol: TCP
    port: 8000
    targetPort: 8000
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # you can specify a value in the `spec.ports[*].nodePort` field.