export const QuestionActionType = {
    ADD_QUESTION: 'ADD_QUESTIOn',
    ADD_SNIPPET: 'ADD_SNIPPET',
    DELETE_SNIPPET: 'DELETE_SNIPPET',
    EDIT_SNIPPET: 'EDIT_SNIPPET',
    ADD_TEST: 'ADD_TEST',
    DELETE_TEST: 'DELETE_TEST'
}