export const QuestionActionType = {
    ADD_QUESTION: 'ADD_QUESTION',
    ADD_SNIPPET: 'ADD_SNIPPET',
    DELETE_SNIPPET: 'DELETE_SNIPPET',
    EDIT_SNIPPET: 'EDIT_SNIPPET',
    ADD_TEST: 'ADD_TEST',
    DELETE_TEST: 'DELETE_TEST',
    CLEAR_STATE: 'CLEAR_STATE'
}